### ISSUE TITLE
StackOverflowError in KafkaConsumerActor

### ISSUE THREAD

**Issue by sebastianvoss** [ovotech/fs2-kafka#14]
I have a very simple consumer which runs into an StackOverflowError after some time (`fs2-kafka 0.16.2`). After increasing `-XX:MaxJavaStackTraceDepth` I located it in `KafkaConsumerActor.scala:223`.

```
Exception in thread "fs2-kafka-consumer-20" java.lang.StackOverflowError
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:505)
	[...]
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
	at scala.collection.MapLike$$anon$1.hasNext(MapLike.scala:186)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:177)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
	at scala.collection.generic.Subtractable.$minus$minus(Subtractable.scala:59)
	at scala.collection.generic.Subtractable.$minus$minus$(Subtractable.scala:59)
	at scala.collection.AbstractSet.$minus$minus(Set.scala:47)
	at scala.collection.SetLike.diff(SetLike.scala:179)
	at scala.collection.SetLike.diff$(SetLike.scala:179)
	at scala.collection.AbstractSet.diff(Set.scala:47)
	at fs2.kafka.KafkaConsumerActor.$anonfun$poll$2(KafkaConsumerActor.scala:223)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:345)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Consumer:

```
val consumerSettings = (executionContext: ExecutionContext) =>
    ConsumerSettings(
      keyDeserializer = new StringDeserializer,
      valueDeserializer = circeJsonDeserializer[Measurement],
      executionContext = executionContext
    )
      .withAutoOffsetReset(AutoOffsetReset.Latest)
      .withAutoCommitInterval(10.seconds)
      .withBootstrapServers("localhost:9092")
      .withGroupId("group")

val topics = NonEmptyList.one("test")

val stream =
        for {
          executionContext <- consumerExecutionContextStream[IO]
          consumer <- consumerStream[IO].using(consumerSettings(executionContext))
          _ <- consumer.subscribe(topics)
          _ <- consumer.stream
            .evalTap[IO](message =>
              processRecord(List(message.record), service)
            )
        } yield ()

stream.compile.drain.as(ExitCode.Success)
```

**Comment by vlovgr** [comment]
Thanks for reporting @sebastianvoss! What Scala version are you using? And how many partitions are there on the topic you're consuming? This looks a bit like a bug in the Scala standard library, given the line in question (`KafkaConsumerActor:223`) is:

```scala
val resume = (assigned intersect requested) diff available
```

where `available` usually is `Map.empty.keySet`, and the overflow occurs in `diff`. Anyway, `diff` is not very efficiently implemented for when `available` is empty, so there's potential to do something better here. But it would be good to be able to reproduce this in a unit test.

**Comment by sebastianvoss** [comment]
Hi @vlovgr, thanks for your quick feedback. I'm using scala `2.12.7` and there is only one partition for the `test` topic. I will try to reproduce it with a minimal example.

**Comment by vlovgr** [comment]
@sebastianvoss I've put together something which hopefully solves this issue in #15. I'll make a new release shortly, please give it a try.

**Comment by sebastianvoss** [comment]
Fantastic! I will give it a try as soon as possible.

**Comment by sebastianvoss** [comment]
In `0.16.2` I got another one coming from https://github.com/ovotech/fs2-kafka/blob/v0.16.2/src/main/scala/fs2/kafka/KafkaConsumerActor.scala#L238. I just updated to `0.16.3` and will get back with my observations.

**Comment by vlovgr** [comment]
@sebastianvoss not sure if it's related, do you happen to have the stack trace from that one?

**Comment by sebastianvoss** [comment]
@vlovgr, quick update. With the new version I'm running into another `StackOverflowError` (see stack trace below).

```
Exception in thread "fs2-kafka-consumer-20" java.lang.StackOverflowError
	at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:234)
	at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:234)
	[...]
	at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:234)
	at scala.collection.TraversableOnce.size(TraversableOnce.scala:106)
	at scala.collection.TraversableOnce.size$(TraversableOnce.scala:104)
	at scala.collection.AbstractTraversable.size(Traversable.scala:104)
	at cats.kernel.instances.MapMonoid.combine(map.scala:62)
	at cats.kernel.instances.MapMonoid.combine(map.scala:57)
	at fs2.kafka.KafkaConsumerActor.handleBatch$1(KafkaConsumerActor.scala:294)
	at fs2.kafka.KafkaConsumerActor.$anonfun$poll$24(KafkaConsumerActor.scala:359)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:345)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:345)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:345)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by vlovgr** [comment]
@sebastianvoss Thanks for the update and the stack trace! That's a different issue though, but will take a look shortly.

**Comment by vlovgr** [comment]
@sebastianvoss v0.16.4 is out with #16 which should fix this issue. Thanks a lot for reporting these!

**Comment by sebastianvoss** [comment]
@vlovgr Sure thing, thanks for the quick fix. I updated and keep an eye on it.

**Comment by sebastianvoss** [comment]
@vlovgr Good news, no more errors so far. Thanks for this great library :thumbsup:.

**Comment by vlovgr** [comment]
@sebastianvoss That's great to hear! Thanks for reporting back. And thanks again for raising this issue, and for the stack traces -- they were essential for tracking this down. 👍
