### ISSUE TITLE
Consumer key deserializer throw exception when key is null

### ISSUE THREAD

**Issue by khajavi** [ovotech/fs2-kafka#220]
When I start consuming from kafka topic, if the messages don't have any key, the consumer throw exception.
Kafka consumer (java api) don't matter if messages don't have key. Is it possible to these messages in fs2-kafka?

```scala
object ConsumerExample extends IOApp {

  import cats.effect._
  import cats.implicits._
  import fs2.kafka._

  val settings =
    ConsumerSettings[IO, String, String](
      keyDeserializer = Deserializer[IO, String],
      valueDeserializer = Deserializer[IO, String]
    ).withAutoOffsetReset(AutoOffsetReset.Earliest)
      .withBootstrapServers("kafka:9092")
      .withGroupId("group")


  def run(args: List[String]): IO[ExitCode] = {
    val stream: fs2.Stream[IO, CommittableConsumerRecord[IO, String, String]] =
      consumerStream(settings)
       .evalTap(_.subscribeTo("queue1"))
        .flatMap(_.stream)


    stream.evalMap(s => IO(println(s))).compile.drain.as(ExitCode.Success)
  }
}
```

```
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:515)
	at fs2.kafka.Deserializer$.$anonfun$string$1(Deserializer.scala:218)
	at fs2.kafka.Deserializer$.$anonfun$lift$1(Deserializer.scala:194)
	at fs2.kafka.Deserializer$$anon$1.deserialize(Deserializer.scala:143)
	at fs2.kafka.ConsumerRecord$.deserializeFromBytes(ConsumerRecord.scala:176)
	at fs2.kafka.ConsumerRecord$.fromJava(ConsumerRecord.scala:187)
	at fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$2(KafkaConsumerActor.scala:325)
	at cats.data.NonEmptyVectorInstances$$anon$1.traverse(NonEmptyVector.scala:295)
	at cats.data.NonEmptyVectorInstances$$anon$1.traverse(NonEmptyVector.scala:243)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19)
	at fs2.kafka.internal.KafkaConsumerActor.$anonfun$records$1(KafkaConsumerActor.scala:323)
	at cats.instances.VectorInstances$$anon$1.$anonfun$traverse$2(vector.scala:78)
	at cats.instances.VectorInstances$$anon$1.loop$2(vector.scala:41)
	at cats.instances.VectorInstances$$anon$1.$anonfun$foldRight$2(vector.scala:42)
	at cats.Eval$.advance(Eval.scala:271)
	at cats.Eval$.loop$1(Eval.scala:350)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
	at cats.Eval$Defer.value(Eval.scala:257)
	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:77)
	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:13)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19)
	at fs2.kafka.internal.KafkaConsumerActor.records(KafkaConsumerActor.scala:320)
	at fs2.kafka.internal.KafkaConsumerActor.$anonfun$poll$2(KafkaConsumerActor.scala:352)
	at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vlovgr** [comment]
You probably want `Option[String]` for the key, where `null` will be deserialized to `None`, as mentioned here: https://ovotech.github.io/fs2-kafka/docs/consumers#deserializers. If you don't need the key at all, you can use `Unit` for the key type.
